### ISSUE TITLE
setup development environment

### ISSUE THREAD

**Issue by neatlife** [glycerine/sshego#6]
![image](https://user-images.githubusercontent.com/4076198/84226144-92922100-ab13-11ea-85ef-be861ec48235.png)

direct run go build will get dependency code crash

**Comment by glycerine** [comment]
The mailgun api changes from time to time.

Feel free to update it to the latest mailgun api and submit an PR.

**Comment by neatlife** [comment]
please check new pr: https://github.com/glycerine/sshego/pull/7

**Comment by glycerine** [comment]
merged, thanks.
